// Auto-generated by Neutron. Do not edit.
declare module "@neutron-build/core" {
  interface NeutronGeneratedRouteMap {
    paths:
    | "/"
    | "/404"
    | "/about"
    | "/blog"
    | `/blog/${string}`
    | "/careers"
    | "/cli"
    | "/contact"
    | "/dash"
    | "/docs"
    | "/docs/*slug"
    | "/observe"
    | "/pricing"
    | "/privacy"
    | "/security"
    | "/status"
    | "/support"
    | "/terms"
    | "/trmnl"
  }
}

export {};
