// Auto-generated by Neutron. Do not edit.
declare module "@neutron-build/core" {
  interface NeutronGeneratedRouteMap {
    paths:
    | "/"
    | "/404"
    | "/about"
    | "/blog"
    | `/blog/${string}`
    | "/careers"
    | "/changelog"
    | "/code"
    | "/communicate"
    | "/contact"
    | "/deploy"
    | "/docs/*slug"
    | "/observe"
    | "/payments"
    | "/pricing"
    | "/privacy"
    | "/router"
    | "/security"
    | "/status"
    | "/support"
    | "/terms"
    | "/trmnl"
  }
}

export {};
