// Auto-generated by Neutron. Do not edit.
declare module "neutron/content" {
  interface ContentCollectionMap {
    "blog": { "title": string; "description": string; "publishedAt": Date; "updatedAt"?: Date; "author": { "name": string; "avatar"?: string; "twitter"?: string; }; "category": "Announcements" | "Engineering" | "Tutorials" | "Guides" | "Comparisons" | "Business" | "AI" | "Security"; "tags": string[]; "image"?: { "src": string; "alt": string; }; "draft": boolean; "featured": boolean; };
    "docs": { "title": string; "description"?: string; "sidebar_label"?: string; "order"?: number; "draft": boolean; };
  }
}
